### ISSUE TITLE
Gear detail page is useless

### ISSUE THREAD

**Issue by TomekFraczek** [ExcursionClub/ExCSystem#107]
Gear detail page should be improved dramatically

  - [x] Display gear picture
  - [x] Display all gear data (dynamically from gear type and custom fields)
  - [x] Show link to edit page if user has change_gear permission
  - [x] Show link to transaction history if user has permission

**Comment by sarahwells12595** [comment]
This isn't very helpful, just want to comment that I like the issue Title

**Comment by estensen** [comment]
@TomekFraczek https://github.com/ExcursionClub/ExCSystem/pull/130 addresses this, right?

**Comment by TomekFraczek** [comment]
Yep. Takes care of three points. And I'm about to add the last one

**Comment by TomekFraczek** [comment]
Added transaction display 7f8bd1c30e2ed610b0bcf40c65a2ea04c8bc806e
