### ISSUE TITLE
Invalid phone numbers for populated data

### ISSUE THREAD

**Issue by estensen** [ExcursionClub/ExCSystem#165]
`populate_database` adds users with invalid phone numbers. When editing a member phone number validation will stop you from saving. Make sure populated users have valid phone numbers.

**Comment by TomekFraczek** [comment]
The validation on phonenumbers is WAAY overkill. Simplified random phone numbers to predictably be valid. 
c3364aa56f51799bc3ebe921a0f8de040ca82116
336c20b52a2185060905ffe295ac6fa11ae10af2
