### ISSUE TITLE
Btn dots not aligned with btns

### ISSUE THREAD

**Issue by estensen** [ExcursionClub/ExCSystem#204]
Small UI bug
The dots on the btns go outside the btns and are still clickable

<img width="702" alt="screenshot 2019-01-29 14 03 02" src="https://user-images.githubusercontent.com/9142800/51910162-ad586f80-23ce-11e9-85be-6bdcd4609036.png">

**Comment by TomekFraczek** [comment]
These tabs no longer exist #310
