### ISSUE TITLE
Staffer modifications

### ISSUE THREAD

**Issue by sarahwells12595** [ExcursionClub/ExCSystem#95]
- [x] Add search bar to staffers

- [x] Add Title to staffer fields (STL, Board, etc)

- [x] Make change staffer page/button

**Comment by sarahwells12595** [comment]
https://github.com/ExcursionClub/ExCSystem/pull/98

**Comment by TomekFraczek** [comment]
The change staffer page already exists by default, but is not linked anywhere (/core/staffer/<id>/change). 

I think the ModelDetailView should be changed to include a link to the change page if the user has the appropriate permission (change_<modelname>)

**Comment by TomekFraczek** [comment]
The fact that the search bar doesn't appear is probably also because of an error in the ViewableModelAdmin
