### ISSUE TITLE
Clicking logout throws Server 500 Error

### ISSUE THREAD

**Issue by thekorfi** [ExcursionClub/ExCSystem#99]
![bildschirmfoto von 2018-10-03 23-30-29](https://user-images.githubusercontent.com/23706723/46440815-dfc9c700-c764-11e8-8e47-02a50d43f31d.png)

When you click the logout button, you will be logged out from the system, but it first throws an error( Server 500)

**Comment by TomekFraczek** [comment]
3688d5adbe7a0a2816bd3bbf929605493ec1db1c
Logout url was 'home', but home page was named 'front page'
